name: "Template"
about: Issue Template for Administrator Permissions
title: Request Template for Administrator Permissions
labels: 'Request'
assignees: mddeepu8
body:
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Information Required
      description: Reason to need Permission
      placeholder: Tell us what you see!
      value: "User Account id"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Permission
      description: Which permission do you need for the selected Repository?
      options:
        - Read (Default)
        - Write
        - Admin
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Repositories
      multiple: true
      options:
        - Admin As a self service
        - Secure Gh Pages
        - XYX
        - ABC
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
