name: Check User Permission
on:
  issues:
    types: [opened, edited]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        id: checkUser
        with:
          require: 'write'
