name: Add bugs to bugs project

on:
  issues:
    types: [opened,edited]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/SynergyDevops/projects/1
          github-token: ${{ secrets.TEST }}
          labeled: bug, new
          label-operator: AND
