name: Check User Permission

on:
  issues:
    types: [opened, edited]
    

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-cool/check-user-permission@main
        id: checkUser
        with:
          require: 'write'
      - name: close
        uses: actions-cool/issues-helper@v2.1.2
        if: steps.checkUser.outputs.check-result == 'false'
        with:
          actions: 'close-issue'
          issue-number: ${{ github.event.issue.number }}
      - name: Get User Input
        id: get_input
        uses: ActionsDesk/parse-issue@master
        with:
          extract_email: '<p>Email of Requester:\s*(.*)</p>'
      - name: Invite User
        id: get-issue-data
        uses: ActionsDesk/invite_user@release/v1
        with:
          CONFIG_PATH: ".github/config.json"
          USER_ROLE: "direct_member"
          EMAIL: ${{ steps.get_input.outputs.['email']}}
      - name: Comment on Issue
        uses: ActionsDesk/add-comment-action@v1
        with:
          message: ${{ steps.get-issue-data.message }}
          status: ${{ steps.get-issue-data.stepStatus }}
