name: Check User Permission

on:
  issues:
    types: [opened, edited]
    

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: mddeepu8/Adminasaselfservice@v2
        with:
          github-token: ${{ secrets.TEST }}
          minimum-permission: admin

      - name: close
        if: steps.checkUser.outputs.check-result == 'false'
        uses: actions-cool/issues-helper@v2.1.2
        with:
          actions: 'close-issue'
          issue-number: ${{ github.event.issue.number }}
