name: Check User Permission

on:
  issues:
    types: [opened, edited]
    

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: lannonbr/repo-permission-check-action@2.0.0
        id: checkUser
        with:
          require: 'write'

      - name: close
        if: steps.checkUser.outputs.check-result == 'false'
        uses: actions-cool/issues-helper@v2.1.2
        with:
          actions: 'close-issue'
          issue-number: ${{ github.event.issue.number }}
