name: Check User Permission

on:
  issues:
    types: [opened, edited]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository permission for user
        id: permission
        uses: sushichop/action-repository-permission@v1
        with:
          required-permission: write
      - name: Display information about permission
        run: |
         echo "A user trying to access is permitted"
         echo "An actual permission was '${{ steps.permission.outputs.actual-permission }}'"
