name: Check User Permission

on:
  issues:
    types: [opened, edited]
    

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: check permission
        uses: sixleaveakkm/check-permission@0.5
        with:
         permission: "admin"
