name: Add a new GitHub issue to the specified project column
on: issues
jobs:
  add-new-issues-to-project-column:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-organization-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
        GITHUB_PROJECT_URL: https://github.com/mddeepu8/securegh-pages
        GITHUB_PROJECT_COLUMN_NAME: To Do
