name: Repository
on: 
  issues:
    types:
      - opened
      - edited
  schedule:
    - cron: 0 0 * * *
env:
  Writer: mddeepu8
  reponame: Adminasaselfservice
  TOKEN: ${{ secrets.TEST }}

jobs:
  repo_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Setup
        if: |
          github.event_name == 'issues' && github.event.action == 'opened,edited'
        uses: seblaporte/github-action-repo-settings-sync@v1.0.0
        with:
          REPOSITORIES: |
            mddeepu8/Adminasaselfservice
          ALLOW_ISSUES: 'true'
          ALLOW_PROJECTS: 'true'
          ALLOW_WIKI: 'true'
          SQUASH_MERGE: 'true'
          MERGE_COMMIT: 'true'
          REBASE_MERGE: 'true'
          DELETE_HEAD: 'false'
          BRANCHES_PROTECTION_NAME: |
            'main'
            'dev'
          BRANCH_PROTECTION_REQUIRED_REVIEWERS: '1'
          BRANCH_PROTECTION_DISMISS: 'true'
          BRANCH_PROTECTION_CODE_OWNERS: 'true'
          BRANCH_PROTECTION_ENFORCE_ADMINS: 'false'
          TOKEN: ${{ secrets.TEST }}
      - name: Adding write Permissions 
        if: contains(github.event.issue.labels.*.name, 'policies'))
        run: | 
          curl \
          -X PUT \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ env.TOKEN }}" \
          https://api.github.com/repos/mddeepu8/Adminasaselfservice/teams/${{ env.Writer }}/repos/philips-internal/${{env.reponame}} \
          -d '{"permission":"push"}'
